# Generated by Django 5.0.3 on 2024-03-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninformations',
            name='renter_information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='books.renterinformations'),
            preserve_default=False,
        ),
    ]
