# Generated by Django 5.0.3 on 2024-03-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_loaninformations_renter_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaninformations',
            options={'verbose_name': 'Empréstimo'},
        ),
        migrations.AlterModelOptions(
            name='renterinformations',
            options={'verbose_name': 'Informações de Locatário'},
        ),
    ]
