# Generated by Django 5.0.3 on 2024-03-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_loaninformations_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaninformations',
            name='renter_information',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Informações de Locatário'},
        ),
        migrations.AlterModelOptions(
            name='loaninformations',
            options={},
        ),
        migrations.AddField(
            model_name='loaninformations',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loaninformations',
            name='renter_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RenterInformations',
        ),
    ]
